# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sriram Venkatesh
tagline:          'A Personal Website '
description:      'Just a small site to describe my life'


author:
  name:           'Sriram Venkatesh'
  url:            https://www.twitter.com/srizzling

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde